language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  pip install -r requirements-dev.txt

script:
  - py.test
  - python scripts/fast_dawid_skene.py --dataset toy --k 2 --mode aggregate --algorithm FDS --print_result --verbose
  - python scripts/fast_dawid_skene.py --dataset toy --mode aggregate --algorithm FDS --print_result --verbose